# Generated by Django 3.1.7 on 2021-07-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPlantillas', '0002_auto_20210617_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEvento', models.CharField(max_length=20)),
                ('fechaI', models.DateField(max_length=20)),
                ('fechaF', models.DateField(max_length=20)),
                ('portrada', models.CharField(max_length=20)),
                ('informacion', models.CharField(max_length=500)),
                ('costo', models.CharField(max_length=20)),
                ('horaInicio', models.CharField(max_length=20)),
                ('horafinal', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=20)),
                ('redeSociales', models.CharField(max_length=500)),
            ],
        ),
    ]
