# Generated by Django 3.1.7 on 2021-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPlantillas', '0003_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='portrada',
            field=models.ImageField(default='null', upload_to='portadas'),
        ),
    ]
