# Generated by Django 3.1.7 on 2021-07-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPlantillas', '0004_auto_20210702_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='portrada',
        ),
        migrations.AddField(
            model_name='eventos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='portadas'),
        ),
    ]
